Booth service feature
JanvanZetten/BazarBackEnd pull request #10
Opened 2018-11-29 14:06 UTC by JanvanZetten

2018-11-29 14:23 UTC, asbamse reviewed
Random spacing
No documentation

2018-11-29 14:23 UTC, asbamse commented on Core/Application/Implementation/BoothService.cs
> +        private readonly IRepository<Booth> _BoothRepo;
Should be _boothRepo

2018-11-29 14:23 UTC, asbamse commented on Core/Application/Implementation/BoothService.cs
> +           return _BoothRepo.Create(newBooth);
Shouldn't the service check for faulty input?

2018-11-29 14:23 UTC, asbamse commented on Core/Application/Implementation/BoothService.cs
> +            return _BoothRepo.GetAll().Where(b => b.Booker.Id == userId).FirstOrDefault();
Could be FirstOrDefault instead of Where

2018-11-29 14:23 UTC, asbamse commented on XUnitTesting/Booth/CreateBoothTest.cs
> +        public CreateBoothTest()
Empty constructor.

2018-11-30 08:27 UTC, Applemelon requested changes

2018-11-30 08:27 UTC, Applemelon commented on Core/Application/Implementation/BoothService.cs
> +            return _BoothRepo.Delete(id);
Doesn't throw an exception if booth doesn't exist

2018-11-30 08:31 UTC, Applemelon submitted a review, later dismissed

2018-11-30 08:40 UTC, Applemelon reviewed
Looks fine to me

2018-11-30 08:42 UTC, Applemelon approved these changes

2018-11-30 08:45 UTC, merged