Development into master after user stories are finished
JanvanZetten/BazarBackEnd pull request #40
Opened 2018-12-06 12:52 UTC by Applemelon

2018-12-06 12:59 UTC, JanvanZetten requested changes

2018-12-06 12:59 UTC, JanvanZetten commented on Core/Application/Implementation/BoothService.cs
> +        public IEnumerable<Booth> GetUsersBooking(string token)
Why is this IEnumerable and not List there should also be a toList() in the code

2018-12-06 12:59 UTC, JanvanZetten commented on Core/Application/IBoothService.cs
> +        IEnumerable<Booth> GetUsersBooking(string token);
Also here it should be list

2018-12-06 12:59 UTC, JanvanZetten commented on Core/Application/Implementation/BoothService.cs
> +            var list = _boothRepository.GetAllIncludeAll().Where(b => b.Booker?.Id == user.Id);
here the toList should be

2018-12-06 13:11 UTC, JanvanZetten approved these changes

2018-12-07 08:23 UTC, Husso1997 approved these changes

2018-12-07 08:23 UTC, merged